---
hero_image: images / clone-wars.png
theme: violet
listed: true
copyedit: true
title: Війни клонів
description: Створіть гру, в якій ви повинні зберегти Землю від космічних монстрів
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Вступ
  - 
    title: Зробіть космічний корабель
  - 
    title: Блискавка
  - 
    title: 'Challenge: improve the lightning'
    challenge: true
  - 
    title: Space-hippos
  - 
    title: Spaceship explosion
  - 
    title: Hippos that disappear
  - 
    title: 'Challenge: життя і рахунок'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Кінець гри
  - 
    title: 'Завдання: вдоскональте свою гру'
    challenge: true
  - 
    title: What next?
