---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Clone wars
description: Maak een spel waarin je de aarde tegen ruimtemonsters moet beschermen
version: 4.1.0
last_tested: 2018/10/11
steps:
  - 
    title: Inleiding
  - 
    title: Maak een ruimteschip
  - 
    title: Bliksemschichten
    completion:
      - engaged
  - 
    title: 'Uitdaging: Bliksemschichten verbeteren'
    challenge: true
  - 
    title: Ruimte-nijlpaarden
  - 
    title: Exploderend ruimteschip
  - 
    title: Verdwijnende nijlpaarden
  - 
    title: 'Uitdaging: levens en score'
    challenge: true
  - 
    title: Ruimte-vleermuis
  - 
    title: Wedstrijd voorbij
    completion:
      - internal
  - 
    title: 'Uitdaging: verbeter je spel'
    challenge: true
  - 
    title: Wat kun je verder nog doen?
