---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Clone wars
description: Maak een spel waarin je de aarde tegen ruimtemonsters moet beschermen
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Maak een ruimteschip
  - 
    title: 'Bliksemschichten'
    challenge: true
  - 
    title: Vliegende ruimte-nijlpaarden
  - 
    title: Exploderend ruimteschip
  - 
    title: Verdwijnende nijlpaarden
  - 
    title: 'Fruit vleermuis'
    challenge: true
  - 
    title: Game over
  - 
    title: 'Uitdaging: verbeter je spel'
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
