---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Clone wars
description: Maak een spel waarin je de aarde tegen ruimtemonsters moet beschermen
version: 4.1.0
last_tested: 2018/10/11
steps:
  - 
    title: Inleiding
  - 
    title: Maak een ruimteschip
  - 
    title: Bliksemschichten
  - 
    title: 'Bliksemschichten'
    challenge: true
  - 
    title: Vliegende ruimte-nijlpaarden
  - 
    title: Exploderend ruimteschip
  - 
    title: Verdwijnende nijlpaarden
  - 
    title: 'Challenge: levens en score'
    challenge: true
  - 
    title: Game over
  - 
    title: Game over
  - 
    title: 'Challenge: verbeter je spel'
    challenge: true
  - 
    title: Wat kun je verder nog doen?
