---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: クローンウォーズ
description: あなたが宇宙モンスターから地球を救わなければならないゲームを作りなさい
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: 前書き
  - 
    title: スペースシップ（宇宙船）を作りましょう
  - 
    title: いなずま
  - 
    title: '課題：雷を改善する'
    challenge: true
  - 
    title: 宇宙カバ
  - 
    title: 宇宙船爆発
  - 
    title: 消えるカバ
  - 
    title: 'チャレンジ：命（いのち）と点数'
    challenge: true
  - 
    title: スペースバット
  - 
    title: Game Over!（ゲーム終了）
  - 
    title: 'チャレンジ：ゲームをより良くする'
    challenge: true
  - 
    title: 次は何をしますか？
