---
hero_image: images/clone-wars.png
theme: ljubičasta
listed: true
copyedit: true
title: Ratovi klonova
description: U ovome projektu naučit ćeš napraviti igricu u kojoj moraš spasiti Zemlju od čudovišta iz svemira.
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Sretan rođendan
  - 
    title: Napravite svemirski brod
  - 
    title: Munje
  - 
    title: 'Izazov: Popravljanje munje'
    challenge: true
  - 
    title: Svemirski nilski konji
  - 
    title: Spaceship explosion
  - 
    title: Hippos that disappear
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Game over
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: Što dalje?
