---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Guerras de Clones
description: Crea un juego en que cual tengas que salvar la Tierra de monstruos espaciales
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Construir la nave espacial
  - 
    title: Rayos
  - 
    title: 'Hipopótamos espaciales voladores'
    challenge: true
  - 
    title: '¡Murciélagos de la fruta!'
  - 
    title: Fin del Juego
  - 
    title: 'Reto: Mejorar el juego'
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Game over
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
