---
hero_image: images/clone-wars.png
theme: violeta
listed: true
copyedit: true
title: Guerras de Clones
description: Crea un juego en que cual tengas que salvar la Tierra de monstruos espaciales
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Introducción
  - 
    title: Haz una nave espacial
  - 
    title: Hipopótamos espaciales voladores
  - 
    title: 'Hipopótamos espaciales voladores'
    challenge: true
  - 
    title: '¡Murciélagos de la fruta!'
  - 
    title: Fin del Juego
  - 
    title: 'Reto: Mejorar el juego'
  - 
    title: 'Desafío: vidas y marcador'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Fin del juego
  - 
    title: 'Desafío: mejora tu juego'
    challenge: true
  - 
    title: 'Reto: Otro disfraz'
