---
hero_image: images/clone-wars.png
theme: fioled
listed: true
copyedit: true
title: Brwydro Clonau
description: Dysga sut i greu gêm lle mae angen achub y Ddaear rhag anghenfilod y gofod
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Creu Llong Ofod
  - 
    title: Mellt
  - 
    title: 'Hipopotamws yn hedfan yn y gofod'
    challenge: true
  - 
    title: Ystlumod Ffrwythau!
  - 
    title: Gêm drosodd
  - 
    title: 'Her: Gwella dy gêm'
  - 
    title: 'Her: bywydau a sgôr'
    challenge: true
  - 
    title: Ystlumod gofod
  - 
    title: Gêm drosodd
  - 
    title: 'Her: gwella dy gêm'
    challenge: true
  - 
    title: Beth nesaf?
