---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Klonkriege
description: Erstelle ein Spiel in dem du den Planet Erde vor den Weltraummonstern retten musst
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Einleitung
  - 
    title: Baue ein Raumschiff
  - 
    title: Fliegende Weltraum-Nilpfherde
  - 
    title: 'Fliegende Weltraum-Nilpfherde'
    challenge: true
  - 
    title: Flughunde!
  - 
    title: Game over
  - 
    title: 'Aufgabe: Verbessere dein  Spiel'
  - 
    title: 'Herausforderung: lebt und punktet'
    challenge: true
  - 
    title: Raumschläger
  - 
    title: Spiel ist aus
  - 
    title: 'Herausforderung: Erstelle mehr Blöcke'
    challenge: true
  - 
    title: 'Zusatzaufgabe: mehr Stifte'
