---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Klonkriege
description: Erstelle ein Spiel in dem du den Planet Erde vor den Weltraummonstern retten musst
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Ein Raumschiff bauen
  - 
    title: Blitze
  - 
    title: 'Fliegende Weltraum-Nilpfherde'
    challenge: true
  - 
    title: Flughunde!
  - 
    title: Game over
  - 
    title: 'Aufgabe: Verbessere dein  Spiel'
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Game over
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
