---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Guerra dos Clones
description: Neste projeto você aprenderá a criar um jogo no qual você terá que salvar a Terra de monstros espaciais.
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Guerra dos Clones
  - 
    title: Make a spaceship
  - 
    title: Lightning bolts
  - 
    title: 'Challenge: improve the lightning'
    challenge: true
  - 
    title: Space-hippos
  - 
    title: Spaceship explosion
  - 
    title: Hippos that disappear
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Game over
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
