---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Guerra dos Clones
description: Neste projeto você aprenderá a criar um jogo no qual você terá que salvar a Terra de monstros espaciais.
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Guerra dos Clones
  - 
    title: Construindo uma espaçonave
  - 
    title: Raios elétricos
  - 
    title: 'Challenge: improve the lightning'
    challenge: true
  - 
    title: Space-hippos
  - 
    title: Spaceship explosion
  - 
    title: Hippos that disappear
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Fim do jogo
  - 
    title: 'Desafio: melhore seu jogo'
    challenge: true
  - 
    title: O que vem depois?
