---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Guerra dos Clones
description: Neste projeto você aprenderá a criar um jogo no qual você terá que salvar a Terra de monstros espaciais.
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Guerra dos Clones
  - 
    title: Construindo uma espaçonave
  - 
    title: Raios elétricos
  - 
    title: 'Desafio: melhore a iluminação'
    challenge: true
  - 
    title: Space-hippos
  - 
    title: Explosão de nave espacial
  - 
    title: Hippos that disappear
  - 
    title: 'Desafio: vidas e placar'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Fim do jogo
  - 
    title: 'Desafio: melhore seu jogo'
    challenge: true
  - 
    title: O que vem depois?
