---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Atak klonów
description: Naucz się, jak stworzyć grę, w której musisz uratować Ziemię przed potworami z kosmosu.
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Wprowadzenie
  - 
    title: Stwórz statek kosmiczny
  - 
    title: Błyskawice
  - 
    title: 'Challenge: improve the lightning'
    challenge: true
  - 
    title: Space-hippos
  - 
    title: Spaceship explosion
  - 
    title: Hippos that disappear
  - 
    title: 'Wyzwanie: życia i punkty'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Koniec gry
  - 
    title: 'Wyzwanie: udoskonal swoją grę'
    challenge: true
  - 
    title: Co następne?
