---
hero_image: images/clone-wars.png
theme: fioletowy
listed: true
copyedit: true
title: Atak klonów
description: Naucz się, jak stworzyć grę, w której musisz uratować Ziemię przed potworami z kosmosu.
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Make a spaceship
  - 
    title: Lightning bolts
  - 
    title: 'Challenge: improve the lightning'
    challenge: true
  - 
    title: Space-hippos
  - 
    title: Spaceship explosion
  - 
    title: Hippos that disappear
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Game over
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
