---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Ratovi klonova
description: Napravi igru u kojoj treba da spasiš Zemlju od svemirskih čudovišta
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Izrada svemirskog broda
  - 
    title: 'Munje'
    challenge: true
  - 
    title: Leteći svemirski nilski konji
  - 
    title: Eksplozija svemirskog broda
  - 
    title: Nilski konji koji nestaju
  - 
    title: 'Slijepi miš sa voćem'
    challenge: true
  - 
    title: Kraj igre
  - 
    title: 'Izazov: poboljšaj svoju igru'
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
