---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: Ratovi klonova
description: Napravi igru u kojoj treba da spasiš Zemlju od svemirskih čudovišta
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Uvod
  - 
    title: Izrada svemirskog broda
  - 
    title: Munje
  - 
    title: 'Munje'
    challenge: true
  - 
    title: Leteći svemirski nilski konji
  - 
    title: Eksplozija svemirskog broda
  - 
    title: Nilski konji koji nestaju
  - 
    title: 'Izazov: životi i rezultat'
    challenge: true
  - 
    title: Kraj igre
  - 
    title: Kraj igre
  - 
    title: 'Izazov: poboljšaj svoju igru'
    challenge: true
  - 
    title: 'Izazov: više olovaka'
