---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: La guerre des clones
description: Crée un jeu dans lequel tu dois sauver la Terre des monstres de l'espace
version: 4.1.0
last_tested: 2018-10-11
steps:
  - 
    title: Introduction
  - 
    title: Crée un vaisseau spatial
  - 
    title: éclairs
  - 
    title: 'Défi : améliore l''éclair'
    challenge: true
  - 
    title: Les Hippos de l'espace
  - 
    title: Explosion du vaisseau spatial
  - 
    title: 'Défi : Améliorez votre jeu'
  - 
    title: 'Défi: vies et score'
    challenge: true
  - 
    title: Chauve-souris de l'espace
  - 
    title: Fin de la partie
  - 
    title: 'Défi : Améliore ton jeu'
    challenge: true
  - 
    title: Que faire ensuite ?
