---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: La guerre des clones
description: Crée un jeu dans lequel tu dois sauver la Terre des monstres de l'espace
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Fabrication d'un vaisseau spatial
  - 
    title: Coup de tonnerre
  - 
    title: 'Hippopotames spatiaux'
    challenge: true
  - 
    title: Une chauve-souris !
  - 
    title: Fin du jeu
  - 
    title: 'Défi : Améliorez votre jeu'
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Game over
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
