---
hero_image: images/clone-wars.png
theme: violet
listed: true
copyedit: true
title: La guerre des clones
description: Crée un jeu dans lequel tu dois sauver la Terre des monstres de l'espace
version: 4
last_tested: 10/11/2018
steps:
  - 
    title: Introduction
  - 
    title: Créer un vaisseau spatial
  - 
    title: éclairs
  - 
    title: 'Hippopotames spatiaux'
    challenge: true
  - 
    title: Une chauve-souris !
  - 
    title: Fin du jeu
  - 
    title: 'Défi : Améliorez votre jeu'
  - 
    title: 'Défi: vie et score'
    challenge: true
  - 
    title: Chauve-souris de l'espace
  - 
    title: Game Over
  - 
    title: 'Défi : Améliorez votre jeu'
    challenge: true
  - 
    title: Que faire ensuite?
