---
hero_image: images/clone-wars.png
theme: viola
listed: true
copyedit: true
title: Guerre dei Cloni
description: Crea un gioco in cui dovrai salvare la Terra dai mostri dello spazio
version: 4.1.0
last_tested: 2018-10-11
steps:
- title: Introduzione
- title: Crea una navicella spaziale
- title: Fulmini
  completion:
  - engaged
- title: 'Sfida: migliora il fulmine'
  challenge: true
- title: Ippopotami spaziali
- title: Esplosione della nave spaziale
- title: Ippopotami che scompaiono
- title: 'Sfida: vite e punteggio'
  challenge: true
- title: Pipistrello spaziale
- title: Partita finita
  completion:
  - internal
- title: 'Sfida: migliora il tuo gioco'
  challenge: true