---
hero_image: images/clone-wars.png
theme: viola
listed: true
copyedit: true
title: Guerre dei Cloni
description: Crea un gioco in cui dovrai salvare la Terra dai mostri dello spazio
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Creare un'Astronave
  - 
    title: Fulmini
  - 
    title: 'Ippopotami Spaziali Volanti'
    challenge: true
  - 
    title: Pipistrelli della Frutta!
  - 
    title: Game over
  - 
    title: 'Sfida: Migliora il tuo gioco'
  - 
    title: 'Challenge: lives and score'
    challenge: true
  - 
    title: Space-bat
  - 
    title: Game over
  - 
    title: 'Challenge: improve your game'
    challenge: true
  - 
    title: What next?
